// Implements the network layer services for the library

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: communication.proto

package communication

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MessageType int32

const (
	MessageType_BROADCAST   MessageType = 0
	MessageType_JOIN        MessageType = 1
	MessageType_WRITE       MessageType = 2
	MessageType_WRITE_BATCH MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "BROADCAST",
		1: "JOIN",
		2: "WRITE",
		3: "WRITE_BATCH",
	}
	MessageType_value = map[string]int32{
		"BROADCAST":   0,
		"JOIN":        1,
		"WRITE":       2,
		"WRITE_BATCH": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_communication_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_communication_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

type RawMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

func (x *RawMessage) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RawMessage) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// Request with a request type and payload in bytes
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=communication.MessageType" json:"type,omitempty"`
	Request []byte      `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Version string      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_BROADCAST
}

func (x *Request) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Request) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Empty response
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{2}
}

var File_communication_proto protoreflect.FileDescriptor

var file_communication_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0a, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6d, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x2a, 0x42, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53, 0x54,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x52, 0x49, 0x54, 0x45,
	0x5f, 0x42, 0x41, 0x54, 0x43, 0x48, 0x10, 0x03, 0x32, 0xcc, 0x07, 0x0a, 0x04, 0x53, 0x65, 0x6e,
	0x64, 0x12, 0x3c, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x42, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x19, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x52, 0x42, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x79,
	0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x41, 0x42, 0x41, 0x53,
	0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0e, 0x50, 0x52, 0x46, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12,
	0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x10, 0x45, 0x43, 0x52, 0x42, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x43, 0x42, 0x43,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x10, 0x45, 0x56, 0x43, 0x42, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0f, 0x4d, 0x56, 0x42, 0x41, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x79, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x13, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x11, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53,
	0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x0f, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x47, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communication_proto_rawDescOnce sync.Once
	file_communication_proto_rawDescData = file_communication_proto_rawDesc
)

func file_communication_proto_rawDescGZIP() []byte {
	file_communication_proto_rawDescOnce.Do(func() {
		file_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_communication_proto_rawDescData)
	})
	return file_communication_proto_rawDescData
}

var file_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_communication_proto_goTypes = []interface{}{
	(MessageType)(0),   // 0: communication.MessageType
	(*RawMessage)(nil), // 1: communication.RawMessage
	(*Request)(nil),    // 2: communication.Request
	(*Empty)(nil),      // 3: communication.Empty
}
var file_communication_proto_depIdxs = []int32{
	0,  // 0: communication.Request.type:type_name -> communication.MessageType
	1,  // 1: communication.Send.SendMsg:input_type -> communication.RawMessage
	2,  // 2: communication.Send.SendRequest:input_type -> communication.Request
	1,  // 3: communication.Send.Join:input_type -> communication.RawMessage
	1,  // 4: communication.Send.RBCSendByteMsg:input_type -> communication.RawMessage
	1,  // 5: communication.Send.ABASendByteMsg:input_type -> communication.RawMessage
	1,  // 6: communication.Send.PRFSendByteMsg:input_type -> communication.RawMessage
	1,  // 7: communication.Send.ECRBCSendByteMsg:input_type -> communication.RawMessage
	1,  // 8: communication.Send.CBCSendByteMsg:input_type -> communication.RawMessage
	1,  // 9: communication.Send.EVCBCSendByteMsg:input_type -> communication.RawMessage
	1,  // 10: communication.Send.MVBASendByteMsg:input_type -> communication.RawMessage
	1,  // 11: communication.Send.RetrieveSendByteMsg:input_type -> communication.RawMessage
	1,  // 12: communication.Send.SimpleSendByteMsg:input_type -> communication.RawMessage
	1,  // 13: communication.Send.EchoSendByteMsg:input_type -> communication.RawMessage
	1,  // 14: communication.Send.GCSendByteMsg:input_type -> communication.RawMessage
	3,  // 15: communication.Send.SendMsg:output_type -> communication.Empty
	1,  // 16: communication.Send.SendRequest:output_type -> communication.RawMessage
	1,  // 17: communication.Send.Join:output_type -> communication.RawMessage
	3,  // 18: communication.Send.RBCSendByteMsg:output_type -> communication.Empty
	3,  // 19: communication.Send.ABASendByteMsg:output_type -> communication.Empty
	3,  // 20: communication.Send.PRFSendByteMsg:output_type -> communication.Empty
	3,  // 21: communication.Send.ECRBCSendByteMsg:output_type -> communication.Empty
	3,  // 22: communication.Send.CBCSendByteMsg:output_type -> communication.Empty
	3,  // 23: communication.Send.EVCBCSendByteMsg:output_type -> communication.Empty
	3,  // 24: communication.Send.MVBASendByteMsg:output_type -> communication.Empty
	3,  // 25: communication.Send.RetrieveSendByteMsg:output_type -> communication.Empty
	3,  // 26: communication.Send.SimpleSendByteMsg:output_type -> communication.Empty
	3,  // 27: communication.Send.EchoSendByteMsg:output_type -> communication.Empty
	3,  // 28: communication.Send.GCSendByteMsg:output_type -> communication.Empty
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_communication_proto_init() }
func file_communication_proto_init() {
	if File_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_proto_goTypes,
		DependencyIndexes: file_communication_proto_depIdxs,
		EnumInfos:         file_communication_proto_enumTypes,
		MessageInfos:      file_communication_proto_msgTypes,
	}.Build()
	File_communication_proto = out.File
	file_communication_proto_rawDesc = nil
	file_communication_proto_goTypes = nil
	file_communication_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendClient is the client API for Send service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendClient interface {
	SendMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RawMessage, error)
	Join(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*RawMessage, error)
	RBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	ABASendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	PRFSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	ECRBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	CBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	EVCBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	MVBASendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	RetrieveSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	SimpleSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	EchoSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
	GCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error)
}

type sendClient struct {
	cc grpc.ClientConnInterface
}

func NewSendClient(cc grpc.ClientConnInterface) SendClient {
	return &sendClient{cc}
}

func (c *sendClient) SendMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RawMessage, error) {
	out := new(RawMessage)
	err := c.cc.Invoke(ctx, "/communication.Send/SendRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) Join(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*RawMessage, error) {
	out := new(RawMessage)
	err := c.cc.Invoke(ctx, "/communication.Send/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) RBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/RBCSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) ABASendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/ABASendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) PRFSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/PRFSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) ECRBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/ECRBCSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) CBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/CBCSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) EVCBCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/EVCBCSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) MVBASendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/MVBASendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) RetrieveSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/RetrieveSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) SimpleSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/SimpleSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) EchoSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/EchoSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendClient) GCSendByteMsg(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/communication.Send/GCSendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendServer is the server API for Send service.
type SendServer interface {
	SendMsg(context.Context, *RawMessage) (*Empty, error)
	SendRequest(context.Context, *Request) (*RawMessage, error)
	Join(context.Context, *RawMessage) (*RawMessage, error)
	RBCSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	ABASendByteMsg(context.Context, *RawMessage) (*Empty, error)
	PRFSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	ECRBCSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	CBCSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	EVCBCSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	MVBASendByteMsg(context.Context, *RawMessage) (*Empty, error)
	RetrieveSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	SimpleSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	EchoSendByteMsg(context.Context, *RawMessage) (*Empty, error)
	GCSendByteMsg(context.Context, *RawMessage) (*Empty, error)
}

// UnimplementedSendServer can be embedded to have forward compatible implementations.
type UnimplementedSendServer struct {
}

func (*UnimplementedSendServer) SendMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (*UnimplementedSendServer) SendRequest(context.Context, *Request) (*RawMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (*UnimplementedSendServer) Join(context.Context, *RawMessage) (*RawMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedSendServer) RBCSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RBCSendByteMsg not implemented")
}
func (*UnimplementedSendServer) ABASendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ABASendByteMsg not implemented")
}
func (*UnimplementedSendServer) PRFSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PRFSendByteMsg not implemented")
}
func (*UnimplementedSendServer) ECRBCSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ECRBCSendByteMsg not implemented")
}
func (*UnimplementedSendServer) CBCSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CBCSendByteMsg not implemented")
}
func (*UnimplementedSendServer) EVCBCSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EVCBCSendByteMsg not implemented")
}
func (*UnimplementedSendServer) MVBASendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MVBASendByteMsg not implemented")
}
func (*UnimplementedSendServer) RetrieveSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveSendByteMsg not implemented")
}
func (*UnimplementedSendServer) SimpleSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleSendByteMsg not implemented")
}
func (*UnimplementedSendServer) EchoSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoSendByteMsg not implemented")
}
func (*UnimplementedSendServer) GCSendByteMsg(context.Context, *RawMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GCSendByteMsg not implemented")
}

func RegisterSendServer(s *grpc.Server, srv SendServer) {
	s.RegisterService(&_Send_serviceDesc, srv)
}

func _Send_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).SendMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/SendRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).SendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).Join(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_RBCSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).RBCSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/RBCSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).RBCSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_ABASendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).ABASendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/ABASendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).ABASendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_PRFSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).PRFSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/PRFSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).PRFSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_ECRBCSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).ECRBCSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/ECRBCSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).ECRBCSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_CBCSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).CBCSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/CBCSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).CBCSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_EVCBCSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).EVCBCSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/EVCBCSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).EVCBCSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_MVBASendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).MVBASendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/MVBASendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).MVBASendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_RetrieveSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).RetrieveSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/RetrieveSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).RetrieveSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_SimpleSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).SimpleSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/SimpleSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).SimpleSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_EchoSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).EchoSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/EchoSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).EchoSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Send_GCSendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).GCSendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Send/GCSendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).GCSendByteMsg(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Send_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Send",
	HandlerType: (*SendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _Send_SendMsg_Handler,
		},
		{
			MethodName: "SendRequest",
			Handler:    _Send_SendRequest_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Send_Join_Handler,
		},
		{
			MethodName: "RBCSendByteMsg",
			Handler:    _Send_RBCSendByteMsg_Handler,
		},
		{
			MethodName: "ABASendByteMsg",
			Handler:    _Send_ABASendByteMsg_Handler,
		},
		{
			MethodName: "PRFSendByteMsg",
			Handler:    _Send_PRFSendByteMsg_Handler,
		},
		{
			MethodName: "ECRBCSendByteMsg",
			Handler:    _Send_ECRBCSendByteMsg_Handler,
		},
		{
			MethodName: "CBCSendByteMsg",
			Handler:    _Send_CBCSendByteMsg_Handler,
		},
		{
			MethodName: "EVCBCSendByteMsg",
			Handler:    _Send_EVCBCSendByteMsg_Handler,
		},
		{
			MethodName: "MVBASendByteMsg",
			Handler:    _Send_MVBASendByteMsg_Handler,
		},
		{
			MethodName: "RetrieveSendByteMsg",
			Handler:    _Send_RetrieveSendByteMsg_Handler,
		},
		{
			MethodName: "SimpleSendByteMsg",
			Handler:    _Send_SimpleSendByteMsg_Handler,
		},
		{
			MethodName: "EchoSendByteMsg",
			Handler:    _Send_EchoSendByteMsg_Handler,
		},
		{
			MethodName: "GCSendByteMsg",
			Handler:    _Send_GCSendByteMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}
